### PR TITLE
fix: move layout from state to class member

### LINKED ISSUE #877: Switching between portrait and landscape orientation UI stucks between two tabs
### Current behaviour

Especially on scrollable tab, when i'm switching between vertical and horizontal device orientation, UI stucks between two tabs but it could be unblocked by a swipe or a press on a tab item

### Expected behaviour

when i'm switching between vertical and horizontal device orientation, UI should stay at same tab 

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

There is a repro in [example](https://github.com/react-native-community/react-native-tab-view/tree/master/example) folder

### Screenshots (if applicable)

Screenrecorder-2019-09-09-16-41-17-382
Sorry for bad quality :/

### What have you tried

Nothing for the moment

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 28
| react-native                 | 0.59.8 (same bug with 0.60.4)
| react-native-tab-view        | 
| react-native-gesture-handler | 1.2.1
| react-native-reanimated      | 1.0.1
| node                         | 10.15.2
| npm                  | 6.9.0

### PR DESCRIPTION
**Pull request by osdnk**
closes #877

Read comment in code

### CODE REVIEW

**Comment by Thebarda** [comment]
That sounds a way better than my PR ! @deefourple

File: src/TabBar.tsx [hunk 1]
```diff
@@ -264,19 +264,17 @@ export default class TabBar<T extends Route> extends React.Component<
...
-        width,
-      },
-    });
+    // Decided not to place layout in state because
+    // onLayout is often called before applying changes
+    // (according to https://facebook.github.io/react-native/docs/view.html#onlayout)
+    // and new state (and related evaluation)
+    // can be called before actually applying new related which might lead
+    // to unexpected position of components.
+    // Furthermore, component gets updated anyway after changing orientation
```
Comment (satya164) [inline src/TabBar.tsx]: I think this is not sufficient. TabBar's layout can change for a variety of reasons, not only orientation, e.g. stuff like margin or width of tab bar changing with `style` prop.

Does adding `this.forceUpdate()` after this seem reasonable?

**Comment by jsamr** [comment]
@satya164 Will we have a release soon to test #909?
